<?php

namespace Model;

use Doctrine\ORM\EntityRepository;

/**
 * KeyRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyRepo extends EntityRepository
{
	public function findRandom()
	{
		return $this->findOneBy(array('active' => true));
	}
}
