<?php

namespace Model;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepo extends EntityRepository
{
	public function findByEmail($email)
	{
		return $this->findOneBy(array('email' => $email));
	}

	public function retrieveReportData()
	{
		$sql = 'SELECT users.source_id, count(users.id) as users_count
			FROM key
			INNER JOIN _user as users ON (users.id = key.user_id)
			GROUP BY users.source_id ORDER BY count(users.id) DESC;';

		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();

		return $stmt->fetchAll();
	}
}
